[package]
name = "asrpro-gtk4"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_12"] }
gio = "0.20"
glib = "0.20"
anyhow = "1.0"

[profile.release]
debug = true
