[package]
name = "asrpro-gtk4"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
gio = "0.19"
glib = "0.19"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"